import type { CarbonResultPoint, CarbonResultSeries, CarbineScenarioResults } from "../domain/carbonResults";
import type { CarbineRunRequest } from "../domain/fvsRunRequest";
import { summarizeInventory } from "../domain/inventorySchema";

export function buildHtmlReport(request: CarbineRunRequest, results: CarbineScenarioResults): string {
  const summary = summarizeInventory(request.inventory);
  const hasCarbonRows = results.series.some((series) => series.points.some((point) => point.selectedPoolTotalCarbonTons !== undefined || point.liveTreeCarbonTons !== undefined));
  const hasOfficialSummaryRows = results.series.some((series) =>
    series.points.some((point) => point.totalVolumeCuFt !== undefined || point.basalAreaFt2PerAcre !== undefined || point.treesPerAcre !== undefined)
  );
  const warning = hasCarbonRows
    ? "<p><strong>Runtime note:</strong> These carbon rows were parsed from official FVS FMIN/CARBREPT output.</p>"
    : hasOfficialSummaryRows
      ? "<p><strong>Runtime note:</strong> These rows were generated from official FVS summary output. CARBINE did not find carbon pool output in this run.</p>"
      : results.isRealFvs
        ? ""
        : "<p><strong>Runtime warning:</strong> These are demo results and were not generated by FVS.</p>";
  const resultHeading = hasCarbonRows ? "Carbon Results" : hasOfficialSummaryRows ? "Official FVS Summary Results" : "Results";
  const scenarioSummary = buildScenarioSummaryTable(results.series);
  const treatmentEffects = buildTreatmentEffectsTable(results.series);
  const scenarioSections = results.series.map((series) => buildScenarioSection(series.scenarioName, series.points)).join("");
  const parserWarnings = results.series.flatMap((series) => series.parserWarnings.map((warningText) => `${series.scenarioName}: ${warningText}`));
  const parserWarningHtml = parserWarnings.length
    ? `<ul>${parserWarnings.map((warningText) => `<li>${escapeHtml(warningText)}</li>`).join("")}</ul>`
    : "";

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>CARBINE report - ${escapeHtml(request.project.projectName)}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 2rem; color: #17231d; }
    h1 { color: #143d2d; }
    h3 { margin-top: 1.5rem; }
    table { border-collapse: collapse; width: 100%; }
    th, td { border: 1px solid #cfd8d2; padding: 0.45rem; text-align: left; }
    th { background: #eef3ee; }
    tr { break-inside: avoid; }
    @media print {
      body { margin: 0.5in; }
      table { page-break-inside: auto; }
      thead { display: table-header-group; }
    }
  </style>
</head>
<body>
  <h1>CARBINE</h1>
  <p><em>Because forest carbon insights need exploring.</em></p>
  <p>Project: ${escapeHtml(request.project.projectName)}<br>Stand: ${escapeHtml(request.project.standName)}<br>Report date: ${new Date().toLocaleDateString()}</p>
  <p>CARBINE is independently developed and is not an official USDA Forest Service product. It is powered by the USDA Forest Service Forest Vegetation Simulator.</p>
  ${warning}
  <h2>Input Summary</h2>
  <p>${summary.recordCount} tree records, ${summary.speciesCount} species, ${summary.totalTreesPerAcre.toFixed(1)} TPA, ${summary.basalAreaFt2PerAcre.toFixed(1)} ft2/ac basal area.</p>
  <h2>${resultHeading}</h2>
  ${scenarioSummary}
  ${treatmentEffects}
  ${scenarioSections}
  <h2>Warnings and Limitations</h2>
  ${parserWarningHtml}
  <p>Soil carbon is excluded. Users are responsible for reviewing inputs, assumptions, variant selection, and interpretation of outputs.</p>
</body>
</html>`;
}

function buildTreatmentEffectsTable(series: CarbonResultSeries[]): string {
  const baseline = series.find((scenario) => scenario.scenarioId === "baseline")
    ?? series.find((scenario) => scenario.scenarioName.toLowerCase() === "no treatment")
    ?? series[0];
  const baselineByYear = new Map(baseline.points.map((point) => [point.year, point]));
  const rows = series
    .filter((scenario) => scenario.scenarioId !== baseline.scenarioId)
    .flatMap((scenario) =>
      scenario.points
        .map((point) => ({ scenario, point, baselinePoint: baselineByYear.get(point.year) }))
        .filter(({ baselinePoint }) => baselinePoint !== undefined)
    )
    .map(
      ({ scenario, point, baselinePoint }) =>
        `<tr>
          <td>${escapeHtml(scenario.scenarioName)}</td>
          <td>${point.year}</td>
          <td>${formatNumber(point.selectedPoolTotalCarbonTons, 1)}</td>
          <td>${formatSignedDelta(point.selectedPoolTotalCarbonTons, baselinePoint?.selectedPoolTotalCarbonTons, 1)}</td>
          <td>${formatNumber(point.liveTreeCarbonTons, 1)}</td>
          <td>${formatSignedDelta(point.liveTreeCarbonTons, baselinePoint?.liveTreeCarbonTons, 1)}</td>
          <td>${formatNumber(point.harvestedCarbonTons, 1)}</td>
          <td>${formatSignedDelta(point.basalAreaFt2PerAcre, baselinePoint?.basalAreaFt2PerAcre, 0)}</td>
          <td>${formatSignedDelta(point.totalVolumeCuFt, baselinePoint?.totalVolumeCuFt, 0)}</td>
        </tr>`
    )
    .join("");

  if (!rows) return "";

  return `<h3>Treatment Effects vs No Treatment</h3>
    <table>
      <thead>
        <tr>
          <th>Scenario</th>
          <th>Year</th>
          <th>Selected pool total</th>
          <th>Change vs baseline</th>
          <th>Live tree carbon</th>
          <th>Change vs baseline</th>
          <th>Removed carbon</th>
          <th>BA change</th>
          <th>Volume change</th>
        </tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>`;
}

function buildScenarioSummaryTable(series: CarbonResultSeries[]): string {
  const rows = series
    .map((scenario) => {
      const carbonPoints = scenario.points.filter((point) => point.selectedPoolTotalCarbonTons !== undefined);
      const firstPoint = carbonPoints[0] ?? scenario.points[0];
      const finalPoint = carbonPoints[carbonPoints.length - 1] ?? scenario.points[scenario.points.length - 1];
      const removedCarbon = scenario.points.reduce((total, point) => total + (point.harvestedCarbonTons ?? 0), 0);
      const firstRemovalYear = scenario.points.find((point) => (point.harvestedCarbonTons ?? 0) > 0)?.year;
      return `<tr>
        <td>${escapeHtml(scenario.scenarioName)}</td>
        <td>${formatNumber(finalPoint?.selectedPoolTotalCarbonTons, 1)}</td>
        <td>${formatNumber(finalPoint?.liveTreeCarbonTons, 1)}</td>
        <td>${formatNumber(removedCarbon, 1)}${firstRemovalYear ? ` (${firstRemovalYear})` : ""}</td>
        <td>${formatDelta(firstPoint?.basalAreaFt2PerAcre, finalPoint?.basalAreaFt2PerAcre, 0)}</td>
        <td>${formatDelta(firstPoint?.treesPerAcre, finalPoint?.treesPerAcre, 0)}</td>
      </tr>`;
    })
    .join("");

  return `<h3>Scenario Summary</h3>
    <table>
      <thead>
        <tr>
          <th>Scenario</th>
          <th>Final selected pool total</th>
          <th>Final live tree carbon</th>
          <th>Total removed carbon</th>
          <th>BA change</th>
          <th>Trees/ac change</th>
        </tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>`;
}

function buildScenarioSection(scenarioName: string, points: CarbonResultPoint[]): string {
  const rows = points
    .map(
      (point) =>
        `<tr>
          <td>${point.year}</td>
          <td>${formatNumber(point.selectedPoolTotalCarbonTons, 1)}</td>
          <td>${formatNumber(point.liveTreeCarbonTons, 1)}</td>
          <td>${formatNumber(point.harvestedCarbonTons, 1)}</td>
          <td>${formatNumber(point.totalVolumeCuFt, 0)}</td>
          <td>${formatNumber(point.merchantableVolumeCuFt, 0)}</td>
          <td>${formatNumber(point.basalAreaFt2PerAcre, 0)}</td>
          <td>${formatNumber(point.treesPerAcre, 0)}</td>
        </tr>`
    )
    .join("");

  return `<h3>${escapeHtml(scenarioName)}</h3>
  ${
    rows
      ? `<table>
          <thead>
            <tr>
              <th>Year</th>
              <th>Selected pool total</th>
              <th>Live tree carbon</th>
              <th>Removed carbon</th>
              <th>Total volume</th>
              <th>Merchantable volume</th>
              <th>Basal area</th>
              <th>Trees/ac</th>
            </tr>
          </thead>
          <tbody>${rows}</tbody>
        </table>`
      : "<p>No parsed rows were produced for this scenario.</p>"
  }`;
}

function formatNumber(value: number | undefined, digits: number): string {
  return value === undefined ? "" : value.toFixed(digits);
}

function formatDelta(start: number | undefined, end: number | undefined, digits: number): string {
  if (start === undefined || end === undefined) return "";
  const delta = end - start;
  return `${delta >= 0 ? "+" : ""}${delta.toFixed(digits)}`;
}

function formatSignedDelta(value: number | undefined, baseline: number | undefined, digits: number): string {
  if (value === undefined || baseline === undefined) return "";
  const delta = value - baseline;
  return `${delta >= 0 ? "+" : ""}${delta.toFixed(digits)}`;
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[char] ?? char));
}
