import type { CarbonResultPoint, CarbonResultSeries, CarbineScenarioResults } from "../domain/carbonResults";
import type { CarbineRunRequest } from "../domain/fvsRunRequest";
import { summarizeInventory } from "../domain/inventorySchema";

export function buildTesterSummary(request: CarbineRunRequest, results?: CarbineScenarioResults): string {
  const inventory = summarizeInventory(request.inventory);
  const lines = [
    "CARBINE Tester Summary",
    "======================",
    "",
    `Generated: ${new Date().toISOString()}`,
    `Project: ${request.project.projectName}`,
    `Stand: ${request.project.standName}`,
    `Variant: ${request.fvs.variant}`,
    `Runtime: ${results ? (results.isRealFvs ? "Real official FVS output" : "Demo output") : "No run results provided"}`,
    "",
    "Input",
    "-----",
    `Inventory records: ${inventory.recordCount}`,
    `Species count: ${inventory.speciesCount}`,
    `Trees/ac: ${inventory.totalTreesPerAcre.toFixed(1)}`,
    `Basal area: ${inventory.basalAreaFt2PerAcre.toFixed(1)} ft2/ac`,
    `Projection: ${request.project.inventoryYear} plus ${request.project.projectionYears} years`,
    `Cycle length: ${request.project.cycleLengthYears ?? 5} years`,
    "Carbon units: US short tons of carbon per acre",
    "",
    "Scenarios",
    "---------",
    ...request.scenarios.map((scenario) =>
      `- ${scenario.name}: ${scenario.type}${scenario.treatmentYears.length ? `, treatment years ${scenario.treatmentYears.join(", ")}` : ""}`
    )
  ];

  if (!results) {
    lines.push("", "Results", "-------", "No results have been run yet.");
  } else {
    lines.push(
      "",
      "Results",
      "-------",
      `Adapter: ${results.adapterName}`,
      `Series count: ${results.series.length}`,
      `Generated by FVS: ${results.isRealFvs ? "yes" : "no"}`,
      "",
      ...results.series.flatMap(formatSeriesSummary),
      ...formatTreatmentEffects(results.series),
      ...formatWarnings(results.series)
    );
  }

  lines.push(
    "",
    "Files to Attach",
    "---------------",
    "- carbine-diagnostics*.json from Report or Advanced",
    "- inventory CSV used for this test",
    "- exported report PDF/HTML, if the report is part of the feedback",
    "- this tester summary text file",
    "",
    "Known Limits",
    "------------",
    "- CARBINE is not an official USDA Forest Service product.",
    "- Soil carbon is excluded.",
    "- Carbon is parsed from official FVS FMIN/CARBREPT output when present.",
    "- Inputs, variant choice, FVS assumptions, and interpretations require professional review."
  );

  return `${lines.join("\n")}\n`;
}

function formatSeriesSummary(series: CarbonResultSeries): string[] {
  const carbonPoints = series.points.filter((point) => point.selectedPoolTotalCarbonTons !== undefined);
  const firstPoint = carbonPoints[0] ?? series.points[0];
  const finalPoint = carbonPoints[carbonPoints.length - 1] ?? series.points[series.points.length - 1];
  const removedCarbon = series.points.reduce((total, point) => total + (point.harvestedCarbonTons ?? 0), 0);

  return [
    `Scenario: ${series.scenarioName}`,
    `  Rows parsed: ${series.points.length}`,
    `  First year: ${firstPoint?.year ?? "none"}`,
    `  Final year: ${finalPoint?.year ?? "none"}`,
    `  Final carbon pool shown: ${formatCarbon(finalPoint?.selectedPoolTotalCarbonTons)}`,
    `  Final live tree carbon: ${formatCarbon(finalPoint?.liveTreeCarbonTons)}`,
    `  Total removed carbon: ${formatCarbon(removedCarbon)}`,
    `  Final basal area: ${formatNumber(finalPoint?.basalAreaFt2PerAcre, 0)} ft2/ac`,
    `  Final volume: ${formatNumber(finalPoint?.totalVolumeCuFt, 0)} cu ft`,
    ""
  ];
}

function formatTreatmentEffects(series: CarbonResultSeries[]): string[] {
  const baseline = series.find((candidate) => candidate.scenarioId === "baseline")
    ?? series.find((candidate) => candidate.scenarioName.toLowerCase() === "no treatment")
    ?? series[0];
  if (!baseline) return [];

  const baselineByYear = new Map(baseline.points.map((point) => [point.year, point]));
  const treatmentLines = series
    .filter((candidate) => candidate.scenarioId !== baseline.scenarioId)
    .flatMap((candidate) => {
      const finalPoint = [...candidate.points].reverse().find((point) => point.selectedPoolTotalCarbonTons !== undefined || point.liveTreeCarbonTons !== undefined)
        ?? candidate.points[candidate.points.length - 1];
      const baselinePoint = finalPoint ? baselineByYear.get(finalPoint.year) : undefined;
      return [
        `${candidate.scenarioName} in ${finalPoint?.year ?? "no year"}: carbon pool shown ${formatSignedDelta(finalPoint?.selectedPoolTotalCarbonTons, baselinePoint?.selectedPoolTotalCarbonTons, 1)}, live tree ${formatSignedDelta(finalPoint?.liveTreeCarbonTons, baselinePoint?.liveTreeCarbonTons, 1)}, volume ${formatSignedDelta(finalPoint?.totalVolumeCuFt, baselinePoint?.totalVolumeCuFt, 0)}`
      ];
    });

  return treatmentLines.length ? ["Treatment Effects vs Baseline", "-----------------------------", ...treatmentLines, ""] : [];
}

function formatWarnings(series: CarbonResultSeries[]): string[] {
  const warnings = series.flatMap((candidate) => candidate.parserWarnings.map((warning) => `${candidate.scenarioName}: ${warning}`));
  return warnings.length ? ["Warnings", "--------", ...warnings.map((warning) => `- ${warning}`), ""] : [];
}

function formatCarbon(value: number | undefined): string {
  return value === undefined ? "not parsed" : `${value.toFixed(1)} short tons C/acre`;
}

function formatNumber(value: number | undefined, digits: number): string {
  return value === undefined ? "not parsed" : value.toFixed(digits);
}

function formatSignedDelta(value: number | undefined, baseline: number | undefined, digits: number): string {
  if (value === undefined || baseline === undefined) return "not parsed";
  const delta = value - baseline;
  return `${delta >= 0 ? "+" : ""}${delta.toFixed(digits)}`;
}
