import type { CarbineScenarioResults } from "../domain/carbonResults";
import type { CarbineRunRequest } from "../domain/fvsRunRequest";
import { validateRunRequest } from "../domain/runValidation";
import { scenarioDisplayName } from "../domain/scenarioSchema";
import type { ValidationResult } from "../domain/validation";
import type { FvsAdapter, FvsRunResult, FvsRuntimeInfo } from "./FvsAdapter";
import { writeInventoryPreview, writeKeywordPreview } from "./keywordWriter";

export class FvsMockAdapter implements FvsAdapter {
  name = "CARBINE demo adapter";
  isRealFvs = false;

  async getRuntimeInfo(): Promise<FvsRuntimeInfo> {
    return {
      adapterName: this.name,
      isRealFvs: false,
      label: "Demo data",
      notes: [
        "This adapter does not run FVS.",
        "Connect FvsWasmAdapter before labeling results as real FVS output."
      ]
    };
  }

  async validateRequest(request: CarbineRunRequest): Promise<ValidationResult> {
    return validateRunRequest(request);
  }

  async runScenario(request: CarbineRunRequest, scenarioId: string): Promise<FvsRunResult> {
    const scenario = request.scenarios.find((candidate) => candidate.id === scenarioId);
    if (!scenario) {
      throw new Error(`Scenario ${scenarioId} was not found.`);
    }

    const base = request.inventory.reduce((sum, record) => sum + record.dbhIn * record.treesPerAcre, 0) * 0.28;
    const treatmentDip = scenario.type === "baseline" ? 0 : 0.88;
    const points = Array.from({ length: Math.floor(request.project.projectionYears / 10) + 1 }, (_, index) => {
      const year = request.project.inventoryYear + index * 10;
      const growth = 1 + index * 0.12;
      const treatmentModifier = scenario.treatmentYears.some((treatmentYear) => year >= treatmentYear) ? treatmentDip : 1;
      const selected = Number((base * growth * treatmentModifier).toFixed(1));
      return {
        year,
        liveTreeCarbonTons: Number((selected * 0.72).toFixed(1)),
        standingDeadCarbonTons: Number((selected * 0.08).toFixed(1)),
        downDeadWoodCarbonTons: Number((selected * 0.1).toFixed(1)),
        biomassCarbonTons: Number((selected * 0.95).toFixed(1)),
        harvestedCarbonTons: scenario.type === "baseline" ? 0 : Number((selected * 0.05).toFixed(1)),
        selectedPoolTotalCarbonTons: selected,
        notes: ["Demo output only; not generated by FVS."]
      };
    });

    return {
      scenarioId,
      success: true,
      warnings: ["Demo output only. Real FVS runtime is not connected."],
      errors: [],
      generatedFiles: {
        keywordFile: writeKeywordPreview(request, scenario),
        inventoryFile: writeInventoryPreview(request),
        runLog: "CARBINE demo adapter generated sample carbon series. No FVS executable was run.",
        rawOutputs: {
          "demo-carbon-output.csv": [
            "year,live_tree_carbon_tons,standing_dead_carbon_tons,down_dead_wood_carbon_tons,biomass_carbon_tons,harvested_carbon_tons,selected_pool_total_carbon_tons",
            ...points.map((point) =>
              [
                point.year,
                point.liveTreeCarbonTons,
                point.standingDeadCarbonTons,
                point.downDeadWoodCarbonTons,
                point.biomassCarbonTons,
                point.harvestedCarbonTons,
                point.selectedPoolTotalCarbonTons
              ].join(",")
            )
          ].join("\n")
        }
      },
      parsedCarbon: {
        scenarioId,
        scenarioName: scenarioDisplayName(scenario),
        units: "tons_carbon",
        points,
        includedPools: ["live_tree", "standing_dead", "down_dead_wood", "biomass", "harvested"],
        excludedPools: ["soil_carbon"],
        fvsSourceFiles: ["demo-carbon-output.csv"],
        parserWarnings: ["Demo parser path; replace with official FVS output parser."]
      }
    };
  }

  async runScenarioSet(request: CarbineRunRequest): Promise<CarbineScenarioResults> {
    const runs = await Promise.all(request.scenarios.map((scenario) => this.runScenario(request, scenario.id)));
    return {
      adapterName: this.name,
      isRealFvs: false,
      generatedAt: new Date().toISOString(),
      series: runs.map((run) => run.parsedCarbon),
      runArtifacts: runs.map((run) => ({
        scenarioId: run.scenarioId,
        scenarioName: run.parsedCarbon.scenarioName,
        ...run.generatedFiles
      }))
    };
  }
}
